name: Merge upstream branches

permissions:
  contents: write

on:
  push:
  schedule:
    - cron: '0 18 * * *' # 每天执行一次
  watch:
    types: [started]

jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream
        run: |
          git pull --unshallow
          git remote add upstream https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web.git
          git fetch upstream
          git checkout main
          git merge --no-edit upstream/main
          git push origin main
          git fetch upstream --tags
          git push --tags
